services:
  - type: web
    name: motive-crew-backend
    env: java
    plan: free
    buildCommand: cd motive-crew-ws && ./gradlew build
    startCommand: cd motive-crew-ws && ./gradlew bootRun
    envVars:
      - key: JAVA_VERSION
        value: 17

