services:
  - type: web
    name: motive-crew-backend
    runtime: java17
    plan: free
    buildCommand: cd motive-crew-ws && ./gradlew build
    startCommand: cd motive-crew-ws && ./gradlew bootRun